
[functions.chat_app]
type = "chat"

[models.openrouter_model]
routing = ["openrouter_provider"]

[models.openrouter_model.providers.openrouter_provider]
type = "openrouter"
model_name = "openai/gpt-4o-mini"

[functions.chat_app.variants.default_variant]
type = "chat_completion"
weight = 1.0
model = "openrouter_model"
